### PR TITLE
Categorize resources to relevant topics

### PR DESCRIPTION
**Pull request by myugan**
I just add new directory that we discussed on this [issue](https://github.com/walidshaari/Certified-Kubernetes-Security-Specialist/issues/26).

### CODE REVIEW

**Comment by walidshaari** [comment]
let me check

**Comment by myugan** [comment]
> 
> 
> some notes:
> 
>     * The TOC, in the beginning, should not have subtopics such as the aqua security webcasts, it's meant to be quick shortcuts based on feedback from one of the users.
> 
>     * love the new section/page,
> 
>     * stargazers page does not exist any longer, need to remove the entry from TOC
> 
>     * It looks like the new page might be missed by the visitors to the repo! how can we highlight it as an extra external resources?

Thanks to review it @walidshaari , for extra resources maybe we can add something like **Table of Contents**? what do you think?

**Review by myugan — COMMENTED** [review]
cc: @walidshaari

**Comment by walidshaari** [comment]
Great, it is not a pull from the latest still, but I see you have fixed the merge conflict. @myugan

**Review by walidshaari — APPROVED** [review]
LGTM @myugan

**Comment by walidshaari** [comment]
Great we need to work on the TOC next

**Pull request merged**
